#!/usr/bin/env -S pkgx bash
# Build a drag-n-drop Weft.dmg.
#
#   packaging/dmg.sh [output-dir]   # default: ./dist
#
# Preferred: `create-dmg` lays Weft.app + the Applications drop-link over a
# branded background (the hexagon mark + mantra, generated by
# packaging/mkbg). If create-dmg is unavailable or fails (e.g. no window
# server), it falls back to a plain hdiutil image that is still a working
# drag-n-drop installer — set WEFT_PLAIN_DMG=1 to force it.
#
# Builds the .app first (via package.sh) unless dist/Weft.app already exists,
# so a release can build + codesign the app, then image it here unchanged.
# For a Gatekeeper-clean install the .app should be signed + notarized and
# the DMG stapled — see .github/workflows/release.yml.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/.." && pwd)"
out="${1:-$root/dist}"
app="$out/Weft.app"
dmg="$out/Weft.dmg"
bg="$here/dmg-background.png"

if [ ! -d "$app" ]; then
  bash "$here/package.sh" "$out"
fi
mkdir -p "$out"
rm -f "$dmg"

# A staging dir holding only Weft.app (create-dmg images a folder's contents;
# the Applications link is added by --app-drop-link).
stage="$(mktemp -d)"
trap 'rm -rf "$stage"' EXIT
cp -R "$app" "$stage/Weft.app"

if command -v create-dmg >/dev/null 2>&1 && [ -z "${WEFT_PLAIN_DMG:-}" ]; then
  echo "==> building branded $dmg (create-dmg)"
  if create-dmg \
        --volname "Weft" \
        --background "$bg" \
        --window-pos 200 120 \
        --window-size 660 420 \
        --icon-size 120 \
        --text-size 13 \
        --icon "Weft.app" 165 250 \
        --app-drop-link 495 250 \
        --hide-extension "Weft.app" \
        --no-internet-enable \
        "$dmg" "$stage"; then
    echo "==> done: $dmg"
    exit 0
  fi
  echo "==> create-dmg failed; falling back to a plain image" >&2
  rm -f "$dmg"
fi

echo "==> building plain $dmg (hdiutil)"
ln -s /Applications "$stage/Applications"
hdiutil create \
    -volname "Weft" \
    -srcfolder "$stage" \
    -fs HFS+ \
    -format UDZO \
    -ov \
    "$dmg" >/dev/null
echo "==> done: $dmg"
